apiVersion: v1
kind: Service
metadata:
  name: ruleengine-cloud-controller
spec:
  ports:
  - name: web
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: grpc
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: ruleengine-cloud-controller
  sessionAffinity: None
  type: ClusterIP