[package]
name = "wasm-transform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walrus = { version = "0.19.0", features = ["parallel"] }
rayon = "1"