apiVersion: v1
kind: ServiceAccount
metadata:
  name: rule
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ruleengine
rules:
- apiGroups: ["devices.kubeedge.io"]
  resources: ["devices", "devicemodels", "devices/status", "devicemodels/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["hit.edu.cn"]
  resources: ["scripts", "scripts/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ruleengine
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ruleengine
subjects:
- kind: ServiceAccount
  name: rule
  namespace: default