apiVersion: v1
kind: Service
metadata:
  name: filter-server
spec:
  ports:
  - name: web
    port: 8003
    protocol: TCP
    targetPort: 8003
  selector:
    app: filter-server
  sessionAffinity: None
  type: ClusterIP